"""
User and authentication models
"""

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import Boolean, CheckConstraint, DateTime
from sqlalchemy import Enum as SQLEnum
from sqlalchemy import ForeignKey, Index, Integer, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import text

from .database import Base


class OnboardingStatus(str, Enum):
    """Onboarding status for users"""

    NOT_STARTED = "NOT_STARTED"
    PARTIAL = "PARTIAL"
    FULLY_ONBOARDED = "FULLY_ONBOARDED"


class AccountType(str, Enum):
    """Account type - creator vs visitor"""

    CREATOR = "creator"
    VISITOR = "visitor"


if TYPE_CHECKING:
    from .custom_domain import CustomDomain
    from .custom_email_domain import CustomEmailDomain
    from .database import Persona
    from .document import Document
    from .linkedin import LinkedInBasicInfo, LinkedInExperience, LinkedInPost
    from .stripe import PersonaAccessPurchase, PlatformStripeSubscription, StripeCustomer
    from .text_session import TextSession
    from .tier_plan import UserSubscription, UserUsageCache
    from .twitter import TwitterProfile
    from .voice_clone import VoiceClone
    from .voice_session import VoiceSession
    from .website import WebsiteScrapeMetadata
    from .widget_token import WidgetToken
    from .youtube import YouTubeVideo


class User(Base):
    """
    Core user table - represents a real person who creates expert personas
    """

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    email: Mapped[str] = mapped_column(Text, nullable=False)
    phone: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    username: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    fullname: Mapped[str] = mapped_column(Text, nullable=False)
    avatar: Mapped[Optional[str]] = mapped_column(Text)
    linkedin_id: Mapped[Optional[str]] = mapped_column(Text)
    linkedin_url: Mapped[Optional[str]] = mapped_column(Text)
    location: Mapped[Optional[str]] = mapped_column(Text)
    company: Mapped[Optional[str]] = mapped_column(Text)
    role: Mapped[Optional[str]] = mapped_column(Text)
    llm_generated_expertise: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True, comment="Short expertise summary generated by LLM from LinkedIn data"
    )
    widget_config: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Widget customization settings (colors, sizes, branding, bubble icon, etc.)",
    )
    email_confirmed: Mapped[bool] = mapped_column(Boolean, server_default="false", nullable=False)
    onboarding_status: Mapped[OnboardingStatus] = mapped_column(
        SQLEnum(OnboardingStatus, name="onboarding_status_enum", create_type=False),
        server_default="NOT_STARTED",
        nullable=False,
    )
    account_type: Mapped[AccountType] = mapped_column(
        String(20),
        server_default="creator",
        nullable=False,
        comment="Account type: creator (creates personas) or visitor (purchases access)",
    )

    # Claim code fields (for account claiming flow)
    claim_code: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    claim_code_expires_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    claim_code_attempts: Mapped[int] = mapped_column(Integer, server_default="0", nullable=False)
    claim_code_generated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    auth_details: Mapped[List["AuthDetail"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    personas: Mapped[List["Persona"]] = relationship(back_populates="user")
    linkedin_basic_info: Mapped[Optional["LinkedInBasicInfo"]] = relationship(
        back_populates="user", uselist=False
    )
    linkedin_posts: Mapped[List["LinkedInPost"]] = relationship(back_populates="user")
    linkedin_experiences: Mapped[List["LinkedInExperience"]] = relationship(back_populates="user")
    twitter_profiles: Mapped[List["TwitterProfile"]] = relationship(back_populates="user")
    documents: Mapped[List["Document"]] = relationship(back_populates="user")
    voice_clones: Mapped[List["VoiceClone"]] = relationship(back_populates="user")
    website_scrapes: Mapped[List["WebsiteScrapeMetadata"]] = relationship(back_populates="user")
    widget_tokens: Mapped[List["WidgetToken"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    youtube_videos: Mapped[List["YouTubeVideo"]] = relationship(back_populates="user")
    subscriptions: Mapped[List["UserSubscription"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    usage_cache: Mapped[Optional["UserUsageCache"]] = relationship(
        back_populates="user", uselist=False
    )
    # Stripe relationships
    stripe_customer: Mapped[Optional["StripeCustomer"]] = relationship(
        back_populates="user", uselist=False, cascade="all, delete-orphan"
    )
    platform_stripe_subscriptions: Mapped[List["PlatformStripeSubscription"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    persona_purchases: Mapped[List["PersonaAccessPurchase"]] = relationship(
        back_populates="purchasing_user"
    )
    custom_domains: Mapped[List["CustomDomain"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    custom_email_domains: Mapped[List["CustomEmailDomain"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    # Session tracking (as persona owner)
    voice_sessions: Mapped[List["VoiceSession"]] = relationship(
        back_populates="owner",
        cascade="all, delete-orphan",
        foreign_keys="[VoiceSession.persona_owner_id]",
    )
    text_sessions: Mapped[List["TextSession"]] = relationship(
        back_populates="owner",
        cascade="all, delete-orphan",
        foreign_keys="[TextSession.persona_owner_id]",
    )

    __table_args__ = (
        UniqueConstraint("email", name="uq_users_email"),
        UniqueConstraint("linkedin_id", name="uq_users_linkedin_id"),
        UniqueConstraint("claim_code", name="uq_users_claim_code"),
        Index("idx_users_email", "email"),
        Index("idx_users_username", "username"),
        Index(
            "uq_users_username_partial",
            "username",
            unique=True,
            postgresql_where=text("username IS NOT NULL"),
        ),
        Index(
            "idx_users_linkedin_id", "linkedin_id", postgresql_where=text("linkedin_id IS NOT NULL")
        ),
        Index(
            "idx_users_claim_code_active",
            "claim_code",
            postgresql_where=text("claim_code IS NOT NULL"),
        ),
        {"comment": "Core user accounts - owns all enriched data"},
    )


class AuthDetail(Base):
    """
    Authentication details for users - supports multiple auth methods

    Each row represents ONE authentication method:
    - OAuth (LinkedIn, Google): Stores encrypted tokens
    - Password: Stores bcrypt hash and security fields
    """

    __tablename__ = "auth_details"

    # Primary key
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )

    # Primary auth method identifier
    auth_type: Mapped[str] = mapped_column(Text, nullable=False)
    # Values: 'linkedin_oauth' | 'google_oauth' | 'password' | 'otp'

    # OAuth fields (nullable, only used for OAuth auth types)
    platform: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    platform_user_id: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    platform_username: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    avatar: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    access_token: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # Encrypted
    refresh_token: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # Encrypted
    token_expiry: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    auth_metadata: Mapped[dict] = mapped_column(
        "metadata", JSONB, server_default="{}", nullable=False
    )

    # Password-specific fields (nullable, only used for password auth)
    hashed_password: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # bcrypt hash
    email_verification_token: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    email_verification_token_expires: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    password_reset_token: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    password_reset_expires: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    failed_login_attempts: Mapped[int] = mapped_column(Integer, server_default="0", nullable=False)
    locked_until: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    last_password_change: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    email_verified_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    user: Mapped["User"] = relationship(back_populates="auth_details")

    __table_args__ = (
        # Each user can have each auth type only once
        UniqueConstraint("user_id", "auth_type", name="uq_auth_details_user_auth_type"),
        # Valid auth types
        CheckConstraint(
            "auth_type IN ('linkedin_oauth', 'google_oauth', 'password', 'otp')",
            name="ck_auth_details_valid_auth_type",
        ),
        # OAuth must have access_token
        CheckConstraint(
            "(auth_type NOT LIKE '%_oauth') OR (access_token IS NOT NULL)",
            name="ck_auth_details_oauth_requires_token",
        ),
        # Password must have hashed_password
        CheckConstraint(
            "(auth_type != 'password') OR (hashed_password IS NOT NULL)",
            name="ck_auth_details_password_requires_hash",
        ),
        # OTP must NOT have hashed_password (passwordless auth)
        CheckConstraint(
            "(auth_type != 'otp') OR (hashed_password IS NULL)",
            name="ck_auth_details_otp_no_password",
        ),
        # Indexes
        Index("idx_auth_details_user_id", "user_id"),
        Index("idx_auth_details_auth_type", "auth_type"),
        Index("idx_auth_details_email_verification_token", "email_verification_token"),
        Index("idx_auth_details_password_reset_token", "password_reset_token"),
        {"comment": "Authentication details per user - supports OAuth and password"},
    )
