/**
 * Expert-related TypeScript types
 */

export interface PublicUserDetails {
  user_id: string;
  username: string;
  email: string;
  fullname: string;
  avatar?: string;
  role: string;
  company_role?: string;
  company?: string;
  job_title?: string;
  website_url?: string;
  linkedin_url?: string;
  location?: string;
}

export interface ExpertProfile {
  id: string;
  email: string;
  firstname: string;
  lastname: string;
  fullname: string;
  username: string;
  avatar: string;
  role: string;
  company_role?: string;
  company?: string;
  linkedin_url?: string | null;
  preferred_email: string;
}

// Chat Session Types
export interface ChatSession {
  session_token: string;
  persona_id: string;
  username: string;
  is_anonymous: boolean;
}

export interface SessionStatus {
  session_token: string;
  user_email?: string;
  persona_id: string;
  is_active: boolean;
  is_valid: boolean;
  is_anonymous: boolean;
  message_count: number;
  email_prompted: boolean;
  email_provided: boolean;
  created_at: string;
  last_accessed: string;
  expires_at: string;
}

export interface ProvideEmailResponse {
  success: boolean;
  email: string;
  previous_conversations: boolean;
  merged_sessions: number;
}

// Attachment types for messages
export interface MessageAttachment {
  id: string;
  filename: string;
  file_type:
    | "pdf"
    | "doc"
    | "docx"
    | "xls"
    | "xlsx"
    | "ppt"
    | "pptx"
    | "png"
    | "jpg"
    | "jpeg";
  file_size: number;
  s3_url: string;
  extraction_status?: "pending" | "processing" | "completed" | "failed";
}

// Message Types
export interface Message {
  id: string;
  content: string;
  sender: "user" | "expert";
  timestamp: Date;
  isStreaming?: boolean;
  sources?: MessageSource[];
  // Attachment support
  attachments?: MessageAttachment[];
  // Calendar support (from voice/text chat agents)
  calendarUrl?: string;
  // Legacy fields for special chat with attachments
  type?: "text" | "attachment";
  hidden?: boolean; // If true, don't render this message in UI
  content_type?: "text" | "pdf";
  url?: string; // URL for attachments (e.g., S3 URL for PDFs)
  /** Structured content generated by agent (blog, report, etc.) */
  contentOutput?: import("./contentOutput").ContentOutputItem;
}

export interface MessageSource {
  source: string;
  title: string;
  content: string;
  context?: string; // AI-generated summary for documents/audio/video, or title for YouTube
  similarity?: number;
  source_url: string;
  type: "social_media" | "website" | "document" | "other";
  verification_note?: string;
}

export interface StreamChatChunk {
  type: "content" | "email_prompt" | "complete" | "error" | "sources";
  chunk?: string;
  message?: string;
  message_count?: number;
  session_token?: string;
  error?: string;
  sources?: MessageSource[];
}

// Request Types
export interface ProvideEmailRequest {
  sessionToken: string;
  email: string;
}

export interface StreamChatRequest {
  sessionToken: string;
  username: string;
  message: string;
  context_window?: number;
  temperature?: number;
}

// Expert Status Types
export interface ExpertStatus {
  chat_enabled: boolean;
  status: "ready" | "processing" | "error";
  message?: string;
}
