"""Add conversation_type field to conversations table

Revision ID: 15fa73ba2dc4
Revises: f95f7928ac89
Create Date: 2025-09-25 20:34:28.172053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15fa73ba2dc4'
down_revision: Union[str, Sequence[str], None] = 'f95f7928ac89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('conversation_type', sa.String(length=50), nullable=False, server_default='text'))

    # Add CHECK constraint to ensure only valid conversation types
    op.create_check_constraint(
        'check_conversation_type',
        'conversations',
        "conversation_type IN ('text', 'voice')"
    )

    # Remove server default after column is added to make future inserts explicit
    op.alter_column('conversations', 'conversation_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop CHECK constraint first
    op.drop_constraint('check_conversation_type', 'conversations', type_='check')

    # Remove conversation_type field from conversations table
    op.drop_column('conversations', 'conversation_type')
    # ### end Alembic commands ###
