"""add_widget_config_to_users

Revision ID: 1aa7dbeebdfb
Revises: c9a28ad8c760
Create Date: 2026-01-23 23:55:14.791995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1aa7dbeebdfb'
down_revision: Union[str, Sequence[str], None] = 'c9a28ad8c760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('widget_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Widget customization settings (colors, sizes, branding, bubble icon, etc.)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'widget_config')
    # ### end Alembic commands ###
