"""add_session_token_to_workflow_sessions

Revision ID: 22af6d89f8de
Revises: 6799ef3448b0
Create Date: 2026-01-28 02:05:09.179209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22af6d89f8de'
down_revision: Union[str, Sequence[str], None] = '6799ef3448b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_sessions', sa.Column('session_token', sa.String(length=255), nullable=True, comment='Session token for linking to conversations (matches conversations.session_id)'))
    op.create_index(op.f('ix_workflow_sessions_session_token'), 'workflow_sessions', ['session_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_sessions_session_token'), table_name='workflow_sessions')
    op.drop_column('workflow_sessions', 'session_token')
    # ### end Alembic commands ###
