"""add_widget_tokens_table

Revision ID: 3dac90beeb35
Revises: e879189085cc
Create Date: 2025-10-22 22:15:50.288028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dac90beeb35'
down_revision: Union[str, Sequence[str], None] = 'e879189085cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False, comment='JWT token prefixed with wgt_'),
    sa.Column('name', sa.Text(), nullable=False, comment="Token name for identification (e.g., 'Main Website', 'Blog Widget')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description with additional details'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Last time this token was used'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='When token was revoked (null = active)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    comment='Widget authentication tokens for chat widget embedding'
    )
    op.create_index('idx_widget_tokens_active', 'widget_tokens', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('idx_widget_tokens_token', 'widget_tokens', ['token'], unique=True)
    op.create_index('idx_widget_tokens_user_id', 'widget_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_widget_tokens_user_id', table_name='widget_tokens')
    op.drop_index('idx_widget_tokens_token', table_name='widget_tokens')
    op.drop_index('idx_widget_tokens_active', table_name='widget_tokens', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('widget_tokens')
    # ### end Alembic commands ###
