"""add max_custom_domains to tier_plans

Revision ID: 5fe416725809
Revises: 5d278baa5ef0
Create Date: 2026-01-17 11:20:00.990356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe416725809'
down_revision: Union[str, None] = '5d278baa5ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tier_plans', sa.Column('max_custom_domains', sa.Integer(), server_default='0', nullable=False, comment='Max custom domains per user (-1 = unlimited)'))
    # ### end Alembic commands ###

    # Update tier-specific custom domain limits
    op.execute(sa.text("UPDATE tier_plans SET max_custom_domains = 0 WHERE id = 0"))  # Free tier
    op.execute(sa.text("UPDATE tier_plans SET max_custom_domains = 10 WHERE id = 1"))  # Pro tier
    op.execute(sa.text("UPDATE tier_plans SET max_custom_domains = 10 WHERE id = 2"))  # Business tier
    op.execute(sa.text("UPDATE tier_plans SET max_custom_domains = -1 WHERE id = 3"))  # Enterprise tier


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tier_plans', 'max_custom_domains')
    # ### end Alembic commands ###
