"""add_recording_fields_to_voice_sessions

Revision ID: 6b98f2f67c4c
Revises: 5fe416725809
Create Date: 2026-01-20 23:27:51.179580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b98f2f67c4c'
down_revision: Union[str, Sequence[str], None] = '5fe416725809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    recording_status_enum = sa.Enum(
        'disabled', 'starting', 'active', 'stopping', 'completed', 'failed', 'stopped',
        name='recording_status_enum'
    )
    recording_status_enum.create(op.get_bind(), checkfirst=True)

    # Add columns
    op.add_column('voice_sessions', sa.Column('egress_id', sa.String(length=255), nullable=True, comment='LiveKit egress ID for tracking recording'))
    op.add_column('voice_sessions', sa.Column('recording_s3_path', sa.Text(), nullable=True, comment='S3 path to recording file (e.g., recordings/{persona_id}/{session_id}.mp4)'))
    op.add_column('voice_sessions', sa.Column('recording_status', sa.Enum('disabled', 'starting', 'active', 'stopping', 'completed', 'failed', 'stopped', name='recording_status_enum'), server_default='disabled', nullable=False, comment='Status of the recording'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_sessions', 'recording_status')
    op.drop_column('voice_sessions', 'recording_s3_path')
    op.drop_column('voice_sessions', 'egress_id')

    # Drop enum type
    recording_status_enum = sa.Enum(name='recording_status_enum')
    recording_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
