"""fix_persona_prompts_history_timezone_columns

Revision ID: 807c772784b4
Revises: d1e2f3a4b5c6
Create Date: 2025-10-06 18:21:55.805154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807c772784b4'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Fix timezone-aware datetime columns in persona_prompts_history table."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert persona_prompts_history datetime columns to timezone-aware
    op.alter_column('persona_prompts_history', 'created_at',
                    type_=sa.DateTime(timezone=True),
                    existing_type=sa.DateTime(),
                    existing_nullable=True)

    op.alter_column('persona_prompts_history', 'updated_at',
                    type_=sa.DateTime(timezone=True),
                    existing_type=sa.DateTime(),
                    existing_nullable=True)

    op.alter_column('persona_prompts_history', 'changed_at',
                    type_=sa.DateTime(timezone=True),
                    existing_type=sa.DateTime(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert persona_prompts_history datetime columns back to non-timezone-aware."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert persona_prompts_history datetime columns to non-timezone-aware
    op.alter_column('persona_prompts_history', 'changed_at',
                    type_=sa.DateTime(),
                    existing_type=sa.DateTime(timezone=True),
                    existing_nullable=False)

    op.alter_column('persona_prompts_history', 'updated_at',
                    type_=sa.DateTime(),
                    existing_type=sa.DateTime(timezone=True),
                    existing_nullable=True)

    op.alter_column('persona_prompts_history', 'created_at',
                    type_=sa.DateTime(),
                    existing_type=sa.DateTime(timezone=True),
                    existing_nullable=True)
    # ### end Alembic commands ###
