"""add_llm_generated_expertise_to_users

Revision ID: a1b2c3d4e5f7
Revises: ca5c192f3e3e
Create Date: 2025-12-09 12:00:00.000000

This migration adds a column to store LLM-generated short expertise summary.
When LinkedIn data is ingested, the long-form summary/description is processed
by an LLM to generate a concise one-line expertise description for use in
persona creation prefilling.
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f7"
down_revision: Union[str, Sequence[str], None] = "ca5c192f3e3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Add llm_generated_expertise column to users table.

    This column stores a short, concise expertise summary generated by an LLM
    from the user's LinkedIn profile data (headline, summary, experiences).

    - Nullable: Yes (populated asynchronously after LinkedIn ingestion)
    - Type: Text (allows for flexible length, typically 100-200 chars)
    - Purpose: Pre-fill persona expertise field during persona creation
    """
    op.add_column(
        "users",
        sa.Column(
            "llm_generated_expertise",
            sa.Text(),
            nullable=True,
            comment="Short expertise summary generated by LLM from LinkedIn data",
        ),
    )


def downgrade() -> None:
    """
    Remove llm_generated_expertise column from users table.

    Note: Data will be lost on downgrade. The expertise can be regenerated
    by re-processing LinkedIn data through the LLM service.
    """
    op.drop_column("users", "llm_generated_expertise")
