"""Add voice_processing_jobs table

Revision ID: ab5934b24d71
Revises: 52fd2e9ac67c
Create Date: 2025-10-06 17:27:51.490084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab5934b24d71'
down_revision: Union[str, Sequence[str], None] = '52fd2e9ac67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('stage_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_processing_jobs_job_id'), 'voice_processing_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_voice_processing_jobs_status'), 'voice_processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_voice_processing_jobs_user_id'), 'voice_processing_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_processing_jobs_user_id'), table_name='voice_processing_jobs')
    op.drop_index(op.f('ix_voice_processing_jobs_status'), table_name='voice_processing_jobs')
    op.drop_index(op.f('ix_voice_processing_jobs_job_id'), table_name='voice_processing_jobs')
    op.drop_table('voice_processing_jobs')
    # ### end Alembic commands ###
