"""merge greeting and summary branches

Revision ID: af1be64edbb7
Revises: 6833bf0ae573, c8d9e0f1a2b3
Create Date: 2025-11-21 16:05:42.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1be64edbb7'
down_revision: Union[str, Sequence[str], None] = ('6833bf0ae573', 'c8d9e0f1a2b3')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
