"""add_max_personas_to_tier_plans

Revision ID: eb90ee4c0a06
Revises: e4f5a6b7c8d9
Create Date: 2026-01-05 10:33:11.545778

Adds max_personas column to tier_plans table to limit persona creation per tier.

Persona limits (from pricing page):
- Free (ID=0): 1 persona
- Pro (ID=1): 3 personas
- Business (ID=2): 30 personas
- Enterprise (ID=3): -1 (unlimited)

Note: -1 means unlimited personas
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb90ee4c0a06"
down_revision: Union[str, Sequence[str], None] = "e4f5a6b7c8d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tier_plans",
        sa.Column(
            "max_personas",
            sa.Integer(),
            server_default="1",
            nullable=False,
            comment="Max personas per user (-1 = unlimited)",
        ),
    )
    # ### end Alembic commands ###

    # Update tier-specific persona limits
    # Free tier (ID=0): 1 persona (already default)
    op.execute(sa.text("UPDATE tier_plans SET max_personas = 1 WHERE id = 0"))

    # Pro tier (ID=1): 3 personas
    op.execute(sa.text("UPDATE tier_plans SET max_personas = 3 WHERE id = 1"))

    # Business tier (ID=2): 30 personas
    op.execute(sa.text("UPDATE tier_plans SET max_personas = 30 WHERE id = 2"))

    # Enterprise tier (ID=3): unlimited (-1)
    op.execute(sa.text("UPDATE tier_plans SET max_personas = -1 WHERE id = 3"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tier_plans", "max_personas")
    # ### end Alembic commands ###
