"""create_persona_prompts_history_table_for_versioning

Revision ID: f784955dd88d
Revises: 6565293fb0c0
Create Date: 2025-10-03 17:11:07.596082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f784955dd88d'
down_revision: Union[str, Sequence[str], None] = '6565293fb0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_prompts_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.Column('persona_username', sa.String(length=100), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=False),
    sa.Column('thinking_style', sa.Text(), nullable=True),
    sa.Column('area_of_expertise', sa.Text(), nullable=True),
    sa.Column('chat_objective', sa.Text(), nullable=True),
    sa.Column('objective_response', sa.Text(), nullable=True),
    sa.Column('example_responses', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=True),
    sa.Column('example_prompt', sa.Text(), nullable=True),
    sa.Column('is_dynamic', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('response_structure', sa.Text(), nullable=True),
    sa.Column('conversation_flow', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_persona_prompts_history_changed_at', 'persona_prompts_history', ['changed_at'], unique=False)
    op.create_index('ix_persona_prompts_history_operation', 'persona_prompts_history', ['operation'], unique=False)
    op.create_index('ix_persona_prompts_history_username_version', 'persona_prompts_history', ['persona_username', 'version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_persona_prompts_history_username_version', table_name='persona_prompts_history', if_exists=True)
    op.drop_index('ix_persona_prompts_history_operation', table_name='persona_prompts_history', if_exists=True)
    op.drop_index('ix_persona_prompts_history_changed_at', table_name='persona_prompts_history', if_exists=True)
    op.drop_table('persona_prompts_history')
    # ### end Alembic commands ###
