"""Add voice_id to personas table

Revision ID: f95f7928ac89
Revises: 3a83dd84ed15
Create Date: 2025-09-13 22:20:13.915994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f95f7928ac89'
down_revision: Union[str, Sequence[str], None] = '3a83dd84ed15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the voice_id column - ignore old tables
    op.add_column('personas', sa.Column('voice_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only remove the voice_id column
    op.drop_column('personas', 'voice_id')
    # ### end Alembic commands ###
