/**
 * LiveKit Topic Constants
 *
 * Centralized constants for all LiveKit data channel topics used in the application.
 * Both text and voice chat modes use these topics for communication between
 * the frontend client and the backend agent.
 */

/**
 * Topics for sending/receiving chat messages
 */
export const LIVEKIT_TOPICS = {
  /**
   * Primary chat topic - used for both sending user messages and receiving agent responses
   * Client → Agent: User text messages
   * Agent → Client: Agent text responses
   */
  CHAT: "lk.chat",

  /**
   * Alternative transcription topic - used by LiveKit's native transcription
   * Agent → Client: Agent transcription output
   */
  TRANSCRIPTION: "lk.transcription",

  /**
   * Legacy chat topic - kept for backwards compatibility
   * @deprecated Use CHAT instead
   */
  LEGACY_CHAT: "chat",

  /**
   * Citations topic - RAG source citations from the agent
   * Agent → Client: Citation sources for the response
   */
  CITATIONS: "citations",

  /**
   * Calendar topic - calendar booking URLs
   * Agent → Client: Calendar scheduling link
   */
  CALENDAR: "calendar",

  /**
   * Document status topic - PDF/document processing status updates
   * Agent → Client: Processing status for uploaded documents
   */
  DOCUMENT_STATUS: "document_status",

  /**
   * Chat error topic - error messages from the agent
   * Agent → Client: Rate limits, validation errors, etc.
   */
  CHAT_ERROR: "chat_error",

  /**
   * Suggested questions topic - starter questions for chat UI
   * Agent → Client: Suggested questions sent on session start
   */
  SUGGESTED_QUESTIONS: "suggested_questions",

  /**
   * Content output topic - structured content generated by the agent
   * Agent → Client: Blog posts, articles, reports and other long-form content
   */
  CONTENT_OUTPUT: "content_output",

  /**
   * Agent status topic - real-time status updates from the agent
   * Agent → Client: searching, fetching, generating, idle
   */
  AGENT_STATUS: "agent_status",
} as const;

/**
 * Type for LiveKit topic values
 */
export type LiveKitTopic = (typeof LIVEKIT_TOPICS)[keyof typeof LIVEKIT_TOPICS];

/**
 * Topics that contain agent text responses
 * These should be handled by TextStreamHandler to avoid duplicates
 */
export const AGENT_TEXT_TOPICS: readonly string[] = [
  LIVEKIT_TOPICS.CHAT,
  LIVEKIT_TOPICS.TRANSCRIPTION,
] as const;

/**
 * Topics that contain metadata (not primary message content)
 * These should be handled by DataReceived handler
 */
export const METADATA_TOPICS: readonly string[] = [
  LIVEKIT_TOPICS.CITATIONS,
  LIVEKIT_TOPICS.CALENDAR,
  LIVEKIT_TOPICS.DOCUMENT_STATUS,
  LIVEKIT_TOPICS.CHAT_ERROR,
  LIVEKIT_TOPICS.SUGGESTED_QUESTIONS,
  LIVEKIT_TOPICS.CONTENT_OUTPUT,
  LIVEKIT_TOPICS.AGENT_STATUS,
] as const;

/**
 * Check if a topic is an agent text topic
 */
export function isAgentTextTopic(topic: string | undefined): boolean {
  return topic !== undefined && AGENT_TEXT_TOPICS.includes(topic);
}

/**
 * Check if a topic is a metadata topic
 */
export function isMetadataTopic(topic: string | undefined): boolean {
  return topic !== undefined && METADATA_TOPICS.includes(topic);
}
