import {
  User,
  Camera,
  MessageSquare,
  Mic,
  Globe,
  Mail,
  Calendar,
  Timer,
  DollarSign,
  BookOpen,
  Shield,
} from "lucide-react";
import type { SettingsSection } from "./types";

export const settingsSections: SettingsSection[] = [
  {
    id: "basic-info",
    label: "Basic Info",
    title: "Basic Information",
    description: "Configure your persona's name, role, and appearance",
    icon: User,
  },
  {
    id: "avatar",
    label: "Avatar",
    title: "Persona Avatar",
    description: "Upload a custom avatar for this persona",
    icon: Camera,
  },
  {
    id: "prompt",
    label: "Prompt Configuration",
    title: "Prompt Configuration",
    description: "Define how your persona thinks and responds",
    icon: MessageSquare,
  },
  {
    id: "voice",
    label: "Voice Agent",
    title: "Voice Agent",
    description: "Enable or disable the voice chat agent for this persona",
    icon: Mic,
  },
  {
    id: "language",
    label: "Language",
    title: "Language Settings",
    description: "Configure response language for your persona",
    icon: Globe,
  },
  {
    id: "email",
    label: "Email Capture",
    title: "Email Capture",
    description: "Configure email collection settings",
    icon: Mail,
  },
  {
    id: "calendar",
    label: "Calendar",
    title: "Calendar Integration",
    description: "Connect your calendar for meeting scheduling",
    icon: Calendar,
  },
  {
    id: "session",
    label: "Session Limits",
    title: "Session Time Limits",
    description: "Configure session duration limits for visitors",
    icon: Timer,
  },
  {
    id: "monetization",
    label: "Monetization",
    title: "Monetization",
    description: "Set pricing and payment options",
    icon: DollarSign,
    requiredTier: "paid",
    showLocked: true,
  },
  {
    id: "knowledge",
    label: "Knowledge Sources",
    title: "Knowledge Sources",
    description: "Manage which knowledge sources this persona uses",
    icon: BookOpen,
  },
  {
    id: "access",
    label: "Access Control",
    title: "Access Control",
    description: "Control who can access this persona",
    icon: Shield,
  },
];
