import type { Message } from "@/types/expert";

/**
 * Format a timestamp for display in transcript
 */
const formatTimestamp = (date: Date): string => {
  return date.toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

/**
 * Generate markdown content from chat messages
 */
export function generateMarkdownTranscript(
  messages: Message[],
  expertName: string,
  metadata?: {
    personaName?: string;
    sessionDate?: Date;
  },
): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Chat Transcript with ${expertName}`);
  lines.push("");

  if (metadata?.personaName) {
    lines.push(`**Persona:** ${metadata.personaName}`);
  }

  const sessionDate = metadata?.sessionDate || new Date();
  lines.push(`**Date:** ${formatTimestamp(sessionDate)}`);
  lines.push(`**Messages:** ${messages.length}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // Messages
  messages.forEach((message) => {
    const sender = message.sender === "user" ? "You" : expertName;
    const time = formatTimestamp(message.timestamp);

    lines.push(`### ${sender}`);
    lines.push(`*${time}*`);
    lines.push("");
    lines.push(message.content);
    lines.push("");

    // Add sources/citations if present
    if (message.sources && message.sources.length > 0) {
      lines.push("**Sources:**");
      message.sources.forEach((source, idx) => {
        const url = source.source_url || "";
        if (url) {
          lines.push(`${idx + 1}. [${source.title}](${url})`);
        } else {
          lines.push(`${idx + 1}. ${source.title}`);
        }
      });
      lines.push("");
    }

    // Add attachments if present
    if (message.attachments && message.attachments.length > 0) {
      lines.push("**Attachments:**");
      message.attachments.forEach((att) => {
        lines.push(`- ${att.filename} (${att.file_type})`);
      });
      lines.push("");
    }

    lines.push("---");
    lines.push("");
  });

  // Footer
  lines.push("");
  lines.push("*Transcript generated by ConvoxAI*");

  return lines.join("\n");
}

/**
 * Generate plain text content from chat messages
 */
export function generateTextTranscript(
  messages: Message[],
  expertName: string,
  metadata?: {
    personaName?: string;
    sessionDate?: Date;
  },
): string {
  const lines: string[] = [];

  // Header
  lines.push(`Chat Transcript with ${expertName}`);
  lines.push("=".repeat(40));
  lines.push("");

  if (metadata?.personaName) {
    lines.push(`Persona: ${metadata.personaName}`);
  }

  const sessionDate = metadata?.sessionDate || new Date();
  lines.push(`Date: ${formatTimestamp(sessionDate)}`);
  lines.push(`Messages: ${messages.length}`);
  lines.push("");
  lines.push("-".repeat(40));
  lines.push("");

  // Messages
  messages.forEach((message) => {
    const sender = message.sender === "user" ? "You" : expertName;
    const time = formatTimestamp(message.timestamp);

    lines.push(`[${time}] ${sender}:`);
    lines.push(message.content);
    lines.push("");

    // Add sources/citations if present
    if (message.sources && message.sources.length > 0) {
      lines.push("Sources:");
      message.sources.forEach((source, idx) => {
        const url = source.source_url || "";
        lines.push(`  ${idx + 1}. ${source.title}${url ? ` - ${url}` : ""}`);
      });
      lines.push("");
    }

    // Add attachments if present
    if (message.attachments && message.attachments.length > 0) {
      lines.push("Attachments:");
      message.attachments.forEach((att) => {
        lines.push(`  - ${att.filename} (${att.file_type})`);
      });
      lines.push("");
    }

    lines.push("-".repeat(40));
    lines.push("");
  });

  return lines.join("\n");
}

/**
 * Download content as a file
 */
export function downloadFile(
  content: string,
  filename: string,
  mimeType: string,
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Download transcript as Markdown file
 */
export function downloadTranscriptAsMarkdown(
  messages: Message[],
  expertName: string,
  username: string,
  metadata?: {
    personaName?: string;
    sessionDate?: Date;
  },
): void {
  const content = generateMarkdownTranscript(messages, expertName, metadata);
  const date = new Date().toISOString().split("T")[0];
  const filename = `chat-transcript-${username}-${date}.md`;
  downloadFile(content, filename, "text/markdown");
}

/**
 * Download transcript as plain text file
 */
export function downloadTranscriptAsText(
  messages: Message[],
  expertName: string,
  username: string,
  metadata?: {
    personaName?: string;
    sessionDate?: Date;
  },
): void {
  const content = generateTextTranscript(messages, expertName, metadata);
  const date = new Date().toISOString().split("T")[0];
  const filename = `chat-transcript-${username}-${date}.txt`;
  downloadFile(content, filename, "text/plain");
}

/**
 * Generate and download transcript as PDF
 * Uses browser's print functionality for PDF generation (no external library needed)
 */
export function downloadTranscriptAsPdf(
  messages: Message[],
  expertName: string,
  username: string,
  metadata?: {
    personaName?: string;
    sessionDate?: Date;
  },
): void {
  const sessionDate = metadata?.sessionDate || new Date();

  // Create HTML content for PDF
  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Chat Transcript - ${expertName}</title>
  <style>
    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #1a1a1a;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }
    .header {
      border-bottom: 2px solid #f59e0b;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      font-size: 24px;
      color: #1a1a1a;
      margin-bottom: 10px;
    }
    .header .meta {
      font-size: 14px;
      color: #666;
    }
    .message {
      margin-bottom: 24px;
      padding-bottom: 24px;
      border-bottom: 1px solid #eee;
    }
    .message:last-child {
      border-bottom: none;
    }
    .message-header {
      display: flex;
      align-items: center;
      gap: 10px;
      margin-bottom: 8px;
    }
    .sender {
      font-weight: 600;
      font-size: 14px;
    }
    .sender.user {
      color: #2563eb;
    }
    .sender.expert {
      color: #d97706;
    }
    .timestamp {
      font-size: 12px;
      color: #888;
    }
    .content {
      font-size: 14px;
      white-space: pre-wrap;
      word-wrap: break-word;
    }
    .sources {
      margin-top: 12px;
      padding: 12px;
      background: #f9fafb;
      border-radius: 8px;
      font-size: 12px;
    }
    .sources-title {
      font-weight: 600;
      color: #666;
      margin-bottom: 6px;
    }
    .source-item {
      color: #2563eb;
      margin-left: 12px;
    }
    .attachments {
      margin-top: 8px;
      font-size: 12px;
      color: #666;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #eee;
      font-size: 12px;
      color: #888;
      text-align: center;
    }
    @media print {
      body {
        padding: 20px;
      }
      .message {
        page-break-inside: avoid;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Chat Transcript with ${expertName}</h1>
    <div class="meta">
      ${metadata?.personaName ? `<div>Persona: ${metadata.personaName}</div>` : ""}
      <div>Date: ${formatTimestamp(sessionDate)}</div>
      <div>Messages: ${messages.length}</div>
    </div>
  </div>
  
  <div class="messages">
    ${messages
      .map((message) => {
        const sender = message.sender === "user" ? "You" : expertName;
        const senderClass = message.sender === "user" ? "user" : "expert";
        const time = formatTimestamp(message.timestamp);

        let sourcesHtml = "";
        if (message.sources && message.sources.length > 0) {
          sourcesHtml = `
            <div class="sources">
              <div class="sources-title">Sources:</div>
              ${message.sources
                .map((source, idx) => {
                  const url = source.source_url || "";
                  return `<div class="source-item">${idx + 1}. ${source.title}${url ? ` - ${url}` : ""}</div>`;
                })
                .join("")}
            </div>
          `;
        }

        let attachmentsHtml = "";
        if (message.attachments && message.attachments.length > 0) {
          attachmentsHtml = `
            <div class="attachments">
              Attachments: ${message.attachments.map((att) => att.filename).join(", ")}
            </div>
          `;
        }

        // Escape HTML in content
        const escapedContent = message.content
          .replace(/&/g, "&amp;")
          .replace(/</g, "&lt;")
          .replace(/>/g, "&gt;")
          .replace(/"/g, "&quot;")
          .replace(/'/g, "&#039;");

        return `
          <div class="message">
            <div class="message-header">
              <span class="sender ${senderClass}">${sender}</span>
              <span class="timestamp">${time}</span>
            </div>
            <div class="content">${escapedContent}</div>
            ${sourcesHtml}
            ${attachmentsHtml}
          </div>
        `;
      })
      .join("")}
  </div>
  
  <div class="footer">
    Transcript generated by ConvoxAI
  </div>
</body>
</html>
  `;

  // Open in new window and trigger print dialog
  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();

    // Wait for content to load, then trigger print
    printWindow.onload = () => {
      printWindow.print();
    };

    // Fallback if onload doesn't fire
    setTimeout(() => {
      printWindow.print();
    }, 500);
  }
}
